[package]
name = "rrsync"
version = "0.0.0"
authors = ["Remi Rampin <r@remirampin.com>"]
description = "A clone of rsync in Rust"
readme = "README.md"
repository = "https://github.com/remram44/rrsync"
keywords = ["sync", "rsync", "data-management", "data-transfer", "file-sharing", "file-transfer"]
license = "BSD-3-Clause"

[dependencies]

[dev-dependencies]
