[package]
name = "rs-sync"
version = "0.1.0"
authors = ["Remi Rampin <remirampin@gmail.com>"]

[dependencies]
adler32 = "1.0"
byteorder = "1.3"
docopt = "1.1"
env_logger = "0.6"
log = "0.4"
serde = "1.0"
sha1 = "0.6"
